FROM node:alpine AS node
RUN mkdir -p /node
WORKDIR /node
COPY package.json package-lock.json /node/
RUN npm install

FROM clojure:temurin-21-tools-deps-bookworm AS builder
ARG VERSION="dev"
ARG SERVER_SOCKET_URL="wss://ogres.app/ws"
RUN mkdir -p /build
WORKDIR /build
COPY --from=node /node/node_modules /build/node_modules
COPY ./ /build
RUN clojure -M -m shadow.cljs.devtools.cli release app --config-merge "{:closure-defines {ogres.app.const/VERSION \"${VERSION}\" ogres.app.const/PATH \"/release/${VERSION}\" ogres.app.const/SOCKET-URL \"${SERVER_SOCKET_URL}\"}}"

FROM alpine/git AS website
RUN mkdir -p /website
WORKDIR /website
RUN git clone --depth=1 --single-branch --branch gh-pages https://github.com/samcf/ogres.git .

FROM nginx:alpine
ARG VERSION="dev"
COPY --from=website /website /usr/share/nginx/html
COPY --from=builder /build/web/release /usr/share/nginx/html/release/${VERSION}
