

import "./cljs-runtime/shadow.module.ogres.app.prepend.js";
SHADOW_ENV.setLoaded("shadow.module.ogres.app.prepend.js");
import "./cljs-runtime/goog.debug.error.js";
SHADOW_ENV.setLoaded("goog.debug.error.js");
import "./cljs-runtime/goog.dom.nodetype.js";
SHADOW_ENV.setLoaded("goog.dom.nodetype.js");
import "./cljs-runtime/goog.asserts.asserts.js";
SHADOW_ENV.setLoaded("goog.asserts.asserts.js");
import "./cljs-runtime/goog.reflect.reflect.js";
SHADOW_ENV.setLoaded("goog.reflect.reflect.js");
import "./cljs-runtime/goog.math.long.js";
SHADOW_ENV.setLoaded("goog.math.long.js");
import "./cljs-runtime/goog.math.integer.js";
SHADOW_ENV.setLoaded("goog.math.integer.js");
import "./cljs-runtime/goog.dom.htmlelement.js";
SHADOW_ENV.setLoaded("goog.dom.htmlelement.js");
import "./cljs-runtime/goog.dom.tagname.js";
SHADOW_ENV.setLoaded("goog.dom.tagname.js");
import "./cljs-runtime/goog.dom.element.js";
SHADOW_ENV.setLoaded("goog.dom.element.js");
import "./cljs-runtime/goog.asserts.dom.js";
SHADOW_ENV.setLoaded("goog.asserts.dom.js");
import "./cljs-runtime/goog.dom.asserts.js";
SHADOW_ENV.setLoaded("goog.dom.asserts.js");
import "./cljs-runtime/goog.functions.functions.js";
SHADOW_ENV.setLoaded("goog.functions.functions.js");
import "./cljs-runtime/goog.string.typedstring.js";
SHADOW_ENV.setLoaded("goog.string.typedstring.js");
import "./cljs-runtime/goog.string.const.js";
SHADOW_ENV.setLoaded("goog.string.const.js");
import "./cljs-runtime/goog.html.trustedtypes.js";
SHADOW_ENV.setLoaded("goog.html.trustedtypes.js");
import "./cljs-runtime/goog.html.safescript.js";
SHADOW_ENV.setLoaded("goog.html.safescript.js");
import "./cljs-runtime/goog.fs.url.js";
SHADOW_ENV.setLoaded("goog.fs.url.js");
import "./cljs-runtime/goog.fs.blob.js";
SHADOW_ENV.setLoaded("goog.fs.blob.js");
import "./cljs-runtime/goog.html.trustedresourceurl.js";
SHADOW_ENV.setLoaded("goog.html.trustedresourceurl.js");
import "./cljs-runtime/goog.string.internal.js";
SHADOW_ENV.setLoaded("goog.string.internal.js");
import "./cljs-runtime/goog.html.safeurl.js";
SHADOW_ENV.setLoaded("goog.html.safeurl.js");
import "./cljs-runtime/goog.html.safestyle.js";
SHADOW_ENV.setLoaded("goog.html.safestyle.js");
import "./cljs-runtime/goog.object.object.js";
SHADOW_ENV.setLoaded("goog.object.object.js");
import "./cljs-runtime/goog.html.safestylesheet.js";
SHADOW_ENV.setLoaded("goog.html.safestylesheet.js");
import "./cljs-runtime/goog.flags.flags.js";
SHADOW_ENV.setLoaded("goog.flags.flags.js");
import "./cljs-runtime/goog.labs.useragent.useragent.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.useragent.js");
import "./cljs-runtime/goog.labs.useragent.util.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.util.js");
import "./cljs-runtime/goog.labs.useragent.highentropy.highentropyvalue.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.highentropy.highentropyvalue.js");
import "./cljs-runtime/goog.labs.useragent.highentropy.highentropydata.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.highentropy.highentropydata.js");
import "./cljs-runtime/goog.labs.useragent.browser.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.browser.js");
import "./cljs-runtime/goog.array.array.js";
SHADOW_ENV.setLoaded("goog.array.array.js");
import "./cljs-runtime/goog.dom.tags.js";
SHADOW_ENV.setLoaded("goog.dom.tags.js");
import "./cljs-runtime/goog.html.safehtml.js";
SHADOW_ENV.setLoaded("goog.html.safehtml.js");
import "./cljs-runtime/goog.html.uncheckedconversions.js";
SHADOW_ENV.setLoaded("goog.html.uncheckedconversions.js");
import "./cljs-runtime/goog.dom.safe.js";
SHADOW_ENV.setLoaded("goog.dom.safe.js");
import "./cljs-runtime/goog.string.string.js";
SHADOW_ENV.setLoaded("goog.string.string.js");
import "./cljs-runtime/goog.collections.maps.js";
SHADOW_ENV.setLoaded("goog.collections.maps.js");
import "./cljs-runtime/goog.structs.structs.js";
SHADOW_ENV.setLoaded("goog.structs.structs.js");
import "./cljs-runtime/goog.uri.utils.js";
SHADOW_ENV.setLoaded("goog.uri.utils.js");
import "./cljs-runtime/goog.uri.uri.js";
SHADOW_ENV.setLoaded("goog.uri.uri.js");
import "./cljs-runtime/goog.string.stringbuffer.js";
SHADOW_ENV.setLoaded("goog.string.stringbuffer.js");
import "./cljs-runtime/cljs.core.js";
SHADOW_ENV.setLoaded("cljs.core.js");
import "./cljs-runtime/clojure.string.js";
SHADOW_ENV.setLoaded("clojure.string.js");
import "./cljs-runtime/shadow.cljs.devtools.client.console.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.console.js");
import "./cljs-runtime/shadow.js.js";
SHADOW_ENV.setLoaded("shadow.js.js");
import "./cljs-runtime/module$node_modules$react_refresh$cjs$react_refresh_runtime_development.js";
SHADOW_ENV.setLoaded("module$node_modules$react_refresh$cjs$react_refresh_runtime_development.js");
import "./cljs-runtime/module$node_modules$react_refresh$runtime.js";
SHADOW_ENV.setLoaded("module$node_modules$react_refresh$runtime.js");
import "./cljs-runtime/uix.dev.js";
SHADOW_ENV.setLoaded("uix.dev.js");
import "./cljs-runtime/ogres.app.preload.js";
SHADOW_ENV.setLoaded("ogres.app.preload.js");
import "./cljs-runtime/goog.labs.useragent.engine.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.engine.js");
import "./cljs-runtime/goog.labs.useragent.platform.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.platform.js");
import "./cljs-runtime/goog.useragent.useragent.js";
SHADOW_ENV.setLoaded("goog.useragent.useragent.js");
import "./cljs-runtime/goog.dom.browserfeature.js";
SHADOW_ENV.setLoaded("goog.dom.browserfeature.js");
import "./cljs-runtime/goog.math.math.js";
SHADOW_ENV.setLoaded("goog.math.math.js");
import "./cljs-runtime/goog.math.coordinate.js";
SHADOW_ENV.setLoaded("goog.math.coordinate.js");
import "./cljs-runtime/goog.math.size.js";
SHADOW_ENV.setLoaded("goog.math.size.js");
import "./cljs-runtime/goog.dom.dom.js";
SHADOW_ENV.setLoaded("goog.dom.dom.js");
import "./cljs-runtime/goog.useragent.product.js";
SHADOW_ENV.setLoaded("goog.useragent.product.js");
import "./cljs-runtime/shadow.json.js";
SHADOW_ENV.setLoaded("shadow.json.js");
import "./cljs-runtime/clojure.set.js";
SHADOW_ENV.setLoaded("clojure.set.js");
import "./cljs-runtime/shadow.cljs.devtools.client.env.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.env.js");
import "./cljs-runtime/goog.dom.inputtype.js";
SHADOW_ENV.setLoaded("goog.dom.inputtype.js");
import "./cljs-runtime/goog.collections.iters.js";
SHADOW_ENV.setLoaded("goog.collections.iters.js");
import "./cljs-runtime/goog.debug.errorcontext.js";
SHADOW_ENV.setLoaded("goog.debug.errorcontext.js");
import "./cljs-runtime/goog.debug.debug.js";
SHADOW_ENV.setLoaded("goog.debug.debug.js");
import "./cljs-runtime/goog.iter.iter.js";
SHADOW_ENV.setLoaded("goog.iter.iter.js");
import "./cljs-runtime/goog.iter.es6.js";
SHADOW_ENV.setLoaded("goog.iter.es6.js");
import "./cljs-runtime/goog.structs.map.js";
SHADOW_ENV.setLoaded("goog.structs.map.js");
import "./cljs-runtime/goog.window.window.js";
SHADOW_ENV.setLoaded("goog.window.window.js");
import "./cljs-runtime/goog.dom.forms.js";
SHADOW_ENV.setLoaded("goog.dom.forms.js");
import "./cljs-runtime/goog.dom.classlist.js";
SHADOW_ENV.setLoaded("goog.dom.classlist.js");
import "./cljs-runtime/goog.dom.vendor.js";
SHADOW_ENV.setLoaded("goog.dom.vendor.js");
import "./cljs-runtime/goog.math.box.js";
SHADOW_ENV.setLoaded("goog.math.box.js");
import "./cljs-runtime/goog.math.irect.js";
SHADOW_ENV.setLoaded("goog.math.irect.js");
import "./cljs-runtime/goog.math.rect.js";
SHADOW_ENV.setLoaded("goog.math.rect.js");
import "./cljs-runtime/goog.style.style.js";
SHADOW_ENV.setLoaded("goog.style.style.js");
import "./cljs-runtime/goog.style.transition.js";
SHADOW_ENV.setLoaded("goog.style.transition.js");
import "./cljs-runtime/cljs.core.async.impl.protocols.js";
SHADOW_ENV.setLoaded("cljs.core.async.impl.protocols.js");
import "./cljs-runtime/cljs.core.async.impl.buffers.js";
SHADOW_ENV.setLoaded("cljs.core.async.impl.buffers.js");
import "./cljs-runtime/goog.debug.entrypointregistry.js";
SHADOW_ENV.setLoaded("goog.debug.entrypointregistry.js");
import "./cljs-runtime/goog.async.nexttick.js";
SHADOW_ENV.setLoaded("goog.async.nexttick.js");
import "./cljs-runtime/cljs.core.async.impl.dispatch.js";
SHADOW_ENV.setLoaded("cljs.core.async.impl.dispatch.js");
import "./cljs-runtime/cljs.core.async.impl.channels.js";
SHADOW_ENV.setLoaded("cljs.core.async.impl.channels.js");
import "./cljs-runtime/cljs.core.async.impl.timers.js";
SHADOW_ENV.setLoaded("cljs.core.async.impl.timers.js");
import "./cljs-runtime/cljs.core.async.impl.ioc_helpers.js";
SHADOW_ENV.setLoaded("cljs.core.async.impl.ioc_helpers.js");
import "./cljs-runtime/cljs.core.async.js";
SHADOW_ENV.setLoaded("cljs.core.async.js");
import "./cljs-runtime/shadow.dom.js";
SHADOW_ENV.setLoaded("shadow.dom.js");
import "./cljs-runtime/clojure.data.js";
SHADOW_ENV.setLoaded("clojure.data.js");
import "./cljs-runtime/shadow.util.js";
SHADOW_ENV.setLoaded("shadow.util.js");
import "./cljs-runtime/shadow.object.js";
SHADOW_ENV.setLoaded("shadow.object.js");
import "./cljs-runtime/shadow.animate.js";
SHADOW_ENV.setLoaded("shadow.animate.js");
import "./cljs-runtime/com.cognitect.transit.util.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.util.js");
import "./cljs-runtime/com.cognitect.transit.delimiters.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.delimiters.js");
import "./cljs-runtime/com.cognitect.transit.caching.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.caching.js");
import "./cljs-runtime/com.cognitect.transit.eq.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.eq.js");
import "./cljs-runtime/com.cognitect.transit.types.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.types.js");
import "./cljs-runtime/com.cognitect.transit.impl.decoder.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.impl.decoder.js");
import "./cljs-runtime/com.cognitect.transit.impl.reader.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.impl.reader.js");
import "./cljs-runtime/com.cognitect.transit.handlers.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.handlers.js");
import "./cljs-runtime/com.cognitect.transit.impl.writer.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.impl.writer.js");
import "./cljs-runtime/com.cognitect.transit.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.js");
import "./cljs-runtime/cognitect.transit.js";
SHADOW_ENV.setLoaded("cognitect.transit.js");
import "./cljs-runtime/shadow.remote.runtime.api.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.api.js");
import "./cljs-runtime/shadow.remote.runtime.shared.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.shared.js");
import "./cljs-runtime/clojure.core.protocols.js";
SHADOW_ENV.setLoaded("clojure.core.protocols.js");
import "./cljs-runtime/shadow.remote.runtime.cljs.js_builtins.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.cljs.js_builtins.js");
import "./cljs-runtime/clojure.datafy.js";
SHADOW_ENV.setLoaded("clojure.datafy.js");
import "./cljs-runtime/cljs.pprint.js";
SHADOW_ENV.setLoaded("cljs.pprint.js");
import "./cljs-runtime/clojure.walk.js";
SHADOW_ENV.setLoaded("clojure.walk.js");
import "./cljs-runtime/cljs.spec.gen.alpha.js";
SHADOW_ENV.setLoaded("cljs.spec.gen.alpha.js");
import "./cljs-runtime/cljs.spec.alpha.js";
SHADOW_ENV.setLoaded("cljs.spec.alpha.js");
import "./cljs-runtime/shadow.remote.runtime.writer.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.writer.js");
import "./cljs-runtime/goog.string.stringformat.js";
SHADOW_ENV.setLoaded("goog.string.stringformat.js");
import "./cljs-runtime/cljs.repl.js";
SHADOW_ENV.setLoaded("cljs.repl.js");
import "./cljs-runtime/shadow.remote.runtime.obj_support.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.obj_support.js");
import "./cljs-runtime/shadow.remote.runtime.tap_support.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.tap_support.js");
import "./cljs-runtime/shadow.remote.runtime.eval_support.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.eval_support.js");
import "./cljs-runtime/shadow.cljs.devtools.client.shared.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.shared.js");
import "./cljs-runtime/shadow.cljs.devtools.client.hud.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.hud.js");
import "./cljs-runtime/shadow.cljs.devtools.client.websocket.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.websocket.js");
import "./cljs-runtime/shadow.cljs.devtools.client.browser.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.browser.js");
import "./cljs-runtime/ogres.app.const.js";
SHADOW_ENV.setLoaded("ogres.app.const.js");
import "./cljs-runtime/module$node_modules$process$browser.js";
SHADOW_ENV.setLoaded("module$node_modules$process$browser.js");
import "./cljs-runtime/module$node_modules$react$cjs$react_development.js";
SHADOW_ENV.setLoaded("module$node_modules$react$cjs$react_development.js");
import "./cljs-runtime/module$node_modules$react$index.js";
SHADOW_ENV.setLoaded("module$node_modules$react$index.js");
import "./cljs-runtime/uix.hooks.alpha.js";
SHADOW_ENV.setLoaded("uix.hooks.alpha.js");
import "./cljs-runtime/uix.compiler.input.js";
SHADOW_ENV.setLoaded("uix.compiler.input.js");
import "./cljs-runtime/uix.compiler.attributes.js";
SHADOW_ENV.setLoaded("uix.compiler.attributes.js");
import "./cljs-runtime/uix.compiler.alpha.js";
SHADOW_ENV.setLoaded("uix.compiler.alpha.js");
import "./cljs-runtime/uix.lib.js";
SHADOW_ENV.setLoaded("uix.lib.js");
import "./cljs-runtime/uix.compiler.aot.js";
SHADOW_ENV.setLoaded("uix.compiler.aot.js");
import "./cljs-runtime/cljs_bean.from.cljs.core.js";
SHADOW_ENV.setLoaded("cljs_bean.from.cljs.core.js");
import "./cljs-runtime/cljs_bean.core.js";
SHADOW_ENV.setLoaded("cljs_bean.core.js");
import "./cljs-runtime/uix.core.js";
SHADOW_ENV.setLoaded("uix.core.js");
import "./cljs-runtime/ogres.app.provider.events.js";
SHADOW_ENV.setLoaded("ogres.app.provider.events.js");
import "./cljs-runtime/cljs.tools.reader.impl.utils.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.utils.js");
import "./cljs-runtime/cljs.tools.reader.reader_types.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.reader_types.js");
import "./cljs-runtime/cljs.tools.reader.impl.inspect.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.inspect.js");
import "./cljs-runtime/cljs.tools.reader.impl.errors.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.errors.js");
import "./cljs-runtime/cljs.tools.reader.impl.commons.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.commons.js");
import "./cljs-runtime/cljs.tools.reader.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.js");
import "./cljs-runtime/cljs.tools.reader.edn.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.edn.js");
import "./cljs-runtime/cljs.reader.js";
SHADOW_ENV.setLoaded("cljs.reader.js");
import "./cljs-runtime/datascript.lru.js";
SHADOW_ENV.setLoaded("datascript.lru.js");
import "./cljs-runtime/me.tonsky.persistent_sorted_set.arrays.js";
SHADOW_ENV.setLoaded("me.tonsky.persistent_sorted_set.arrays.js");
import "./cljs-runtime/me.tonsky.persistent_sorted_set.js";
SHADOW_ENV.setLoaded("me.tonsky.persistent_sorted_set.js");
import "./cljs-runtime/datascript.db.js";
SHADOW_ENV.setLoaded("datascript.db.js");
import "./cljs-runtime/datascript.impl.entity.js";
SHADOW_ENV.setLoaded("datascript.impl.entity.js");
import "./cljs-runtime/datascript.built_ins.js";
SHADOW_ENV.setLoaded("datascript.built_ins.js");
import "./cljs-runtime/datascript.pull_parser.js";
SHADOW_ENV.setLoaded("datascript.pull_parser.js");
import "./cljs-runtime/datascript.pull_api.js";
SHADOW_ENV.setLoaded("datascript.pull_api.js");
import "./cljs-runtime/clojure.edn.js";
SHADOW_ENV.setLoaded("clojure.edn.js");
import "./cljs-runtime/datascript.storage.js";
SHADOW_ENV.setLoaded("datascript.storage.js");
import "./cljs-runtime/datascript.serialize.js";
SHADOW_ENV.setLoaded("datascript.serialize.js");
import "./cljs-runtime/datascript.parser.js";
SHADOW_ENV.setLoaded("datascript.parser.js");
import "./cljs-runtime/datascript.query.js";
SHADOW_ENV.setLoaded("datascript.query.js");
import "./cljs-runtime/datascript.util.js";
SHADOW_ENV.setLoaded("datascript.util.js");
import "./cljs-runtime/datascript.core.js";
SHADOW_ENV.setLoaded("datascript.core.js");
import "./cljs-runtime/ogres.app.util.js";
SHADOW_ENV.setLoaded("ogres.app.util.js");
import "./cljs-runtime/ogres.app.geom.js";
SHADOW_ENV.setLoaded("ogres.app.geom.js");
import "./cljs-runtime/ogres.app.events.js";
SHADOW_ENV.setLoaded("ogres.app.events.js");
import "./cljs-runtime/datascript.transit.js";
SHADOW_ENV.setLoaded("datascript.transit.js");
import "./cljs-runtime/shadow.cljs.modern.js";
SHADOW_ENV.setLoaded("shadow.cljs.modern.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$utils$utf8.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$utils$utf8.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$ExtData.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$ExtData.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$DecodeError.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$DecodeError.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$utils$int.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$utils$int.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$timestamp.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$timestamp.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$ExtensionCodec.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$ExtensionCodec.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$utils$typedArrays.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$utils$typedArrays.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$Encoder.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$Encoder.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$encode.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$encode.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$utils$prettyByte.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$utils$prettyByte.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$CachedKeyDecoder.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$CachedKeyDecoder.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$Decoder.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$Decoder.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$decode.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$decode.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$utils$stream.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$utils$stream.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$decodeAsync.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$decodeAsync.js");
import "./cljs-runtime/module$node_modules$$msgpack$msgpack$dist$index.js";
SHADOW_ENV.setLoaded("module$node_modules$$msgpack$msgpack$dist$index.js");
import "./cljs-runtime/ogres.app.provider.idb.js";
SHADOW_ENV.setLoaded("ogres.app.provider.idb.js");
import "./cljs-runtime/ogres.app.provider.state.js";
SHADOW_ENV.setLoaded("ogres.app.provider.state.js");
import "./cljs-runtime/ogres.app.provider.dispatch.js";
SHADOW_ENV.setLoaded("ogres.app.provider.dispatch.js");
import "./cljs-runtime/ogres.app.provider.image.js";
SHADOW_ENV.setLoaded("ogres.app.provider.image.js");
import "./cljs-runtime/module$node_modules$scheduler$cjs$scheduler_development.js";
SHADOW_ENV.setLoaded("module$node_modules$scheduler$cjs$scheduler_development.js");
import "./cljs-runtime/module$node_modules$scheduler$index.js";
SHADOW_ENV.setLoaded("module$node_modules$scheduler$index.js");
import "./cljs-runtime/module$node_modules$react_dom$cjs$react_dom_development.js";
SHADOW_ENV.setLoaded("module$node_modules$react_dom$cjs$react_dom_development.js");
import "./cljs-runtime/module$node_modules$react_dom$index.js";
SHADOW_ENV.setLoaded("module$node_modules$react_dom$index.js");
import "./cljs-runtime/module$node_modules$react_dom$cjs$react_dom_client_development.js";
SHADOW_ENV.setLoaded("module$node_modules$react_dom$cjs$react_dom_client_development.js");
import "./cljs-runtime/module$node_modules$react_dom$client.js";
SHADOW_ENV.setLoaded("module$node_modules$react_dom$client.js");
import "./cljs-runtime/uix.dom.js";
SHADOW_ENV.setLoaded("uix.dom.js");
import "./cljs-runtime/ogres.app.provider.portal.js";
SHADOW_ENV.setLoaded("ogres.app.provider.portal.js");
import "./cljs-runtime/module$node_modules$$rwh$keystrokes$dist$keystrokes_umd_cjs.js";
SHADOW_ENV.setLoaded("module$node_modules$$rwh$keystrokes$dist$keystrokes_umd_cjs.js");
import "./cljs-runtime/ogres.app.hooks.js";
SHADOW_ENV.setLoaded("ogres.app.hooks.js");
import "./cljs-runtime/ogres.app.component.js";
SHADOW_ENV.setLoaded("ogres.app.component.js");
import "./cljs-runtime/ogres.app.component.error.js";
SHADOW_ENV.setLoaded("ogres.app.component.error.js");
import "./cljs-runtime/ogres.app.provider.release.js";
SHADOW_ENV.setLoaded("ogres.app.provider.release.js");
import "./cljs-runtime/ogres.app.component.panel_data.js";
SHADOW_ENV.setLoaded("ogres.app.component.panel_data.js");
import "./cljs-runtime/ogres.app.component.panel_initiative.js";
SHADOW_ENV.setLoaded("ogres.app.component.panel_initiative.js");
import "./cljs-runtime/ogres.app.component.panel_lobby.js";
SHADOW_ENV.setLoaded("ogres.app.component.panel_lobby.js");
import "./cljs-runtime/ogres.app.component.panel_scene.js";
SHADOW_ENV.setLoaded("ogres.app.component.panel_scene.js");
import "./cljs-runtime/module$node_modules$$dnd_kit$core$node_modules$$dnd_kit$utilities$dist$utilities_cjs_development.js";
SHADOW_ENV.setLoaded("module$node_modules$$dnd_kit$core$node_modules$$dnd_kit$utilities$dist$utilities_cjs_development.js");
import "./cljs-runtime/module$node_modules$$dnd_kit$core$node_modules$$dnd_kit$utilities$dist$index.js";
SHADOW_ENV.setLoaded("module$node_modules$$dnd_kit$core$node_modules$$dnd_kit$utilities$dist$index.js");
import "./cljs-runtime/module$node_modules$$dnd_kit$core$node_modules$$dnd_kit$accessibility$dist$accessibility_cjs_development.js";
SHADOW_ENV.setLoaded("module$node_modules$$dnd_kit$core$node_modules$$dnd_kit$accessibility$dist$accessibility_cjs_development.js");
import "./cljs-runtime/module$node_modules$$dnd_kit$core$node_modules$$dnd_kit$accessibility$dist$index.js";
SHADOW_ENV.setLoaded("module$node_modules$$dnd_kit$core$node_modules$$dnd_kit$accessibility$dist$index.js");
import "./cljs-runtime/module$node_modules$$dnd_kit$core$dist$core_cjs_development.js";
SHADOW_ENV.setLoaded("module$node_modules$$dnd_kit$core$dist$core_cjs_development.js");
import "./cljs-runtime/module$node_modules$$dnd_kit$core$dist$index.js";
SHADOW_ENV.setLoaded("module$node_modules$$dnd_kit$core$dist$index.js");
import "./cljs-runtime/ogres.app.component.panel_tokens.js";
SHADOW_ENV.setLoaded("ogres.app.component.panel_tokens.js");
import "./cljs-runtime/ogres.app.component.panel.js";
SHADOW_ENV.setLoaded("ogres.app.component.panel.js");
import "./cljs-runtime/ogres.app.component.scene_draw.js";
SHADOW_ENV.setLoaded("ogres.app.component.scene_draw.js");
import "./cljs-runtime/ogres.app.component.scene_pattern.js";
SHADOW_ENV.setLoaded("ogres.app.component.scene_pattern.js");
import "./cljs-runtime/ogres.app.component.scene_context_menu.js";
SHADOW_ENV.setLoaded("ogres.app.component.scene_context_menu.js");
import "./cljs-runtime/module$node_modules$react_is$cjs$react_is_development.js";
SHADOW_ENV.setLoaded("module$node_modules$react_is$cjs$react_is_development.js");
import "./cljs-runtime/module$node_modules$react_is$index.js";
SHADOW_ENV.setLoaded("module$node_modules$react_is$index.js");
import "./cljs-runtime/module$node_modules$object_assign$index.js";
SHADOW_ENV.setLoaded("module$node_modules$object_assign$index.js");
import "./cljs-runtime/module$node_modules$prop_types$lib$ReactPropTypesSecret.js";
SHADOW_ENV.setLoaded("module$node_modules$prop_types$lib$ReactPropTypesSecret.js");
import "./cljs-runtime/module$node_modules$prop_types$lib$has.js";
SHADOW_ENV.setLoaded("module$node_modules$prop_types$lib$has.js");
import "./cljs-runtime/module$node_modules$prop_types$checkPropTypes.js";
SHADOW_ENV.setLoaded("module$node_modules$prop_types$checkPropTypes.js");
import "./cljs-runtime/module$node_modules$prop_types$factoryWithTypeCheckers.js";
SHADOW_ENV.setLoaded("module$node_modules$prop_types$factoryWithTypeCheckers.js");
import "./cljs-runtime/module$node_modules$prop_types$index.js";
SHADOW_ENV.setLoaded("module$node_modules$prop_types$index.js");
import "./cljs-runtime/module$node_modules$$babel$runtime$helpers$interopRequireDefault.js";
SHADOW_ENV.setLoaded("module$node_modules$$babel$runtime$helpers$interopRequireDefault.js");
import "./cljs-runtime/module$node_modules$dom_helpers$cjs$hasClass.js";
SHADOW_ENV.setLoaded("module$node_modules$dom_helpers$cjs$hasClass.js");
import "./cljs-runtime/module$node_modules$dom_helpers$cjs$addClass.js";
SHADOW_ENV.setLoaded("module$node_modules$dom_helpers$cjs$addClass.js");
import "./cljs-runtime/module$node_modules$dom_helpers$cjs$removeClass.js";
SHADOW_ENV.setLoaded("module$node_modules$dom_helpers$cjs$removeClass.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$config.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$config.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$utils$PropTypes.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$utils$PropTypes.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$TransitionGroupContext.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$TransitionGroupContext.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$utils$reflow.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$utils$reflow.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$Transition.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$Transition.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$CSSTransition.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$CSSTransition.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$utils$ChildMapping.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$utils$ChildMapping.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$TransitionGroup.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$TransitionGroup.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$ReplaceTransition.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$ReplaceTransition.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$SwitchTransition.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$SwitchTransition.js");
import "./cljs-runtime/module$node_modules$react_transition_group$cjs$index.js";
SHADOW_ENV.setLoaded("module$node_modules$react_transition_group$cjs$index.js");
import "./cljs-runtime/ogres.app.component.scene_objects.js";
SHADOW_ENV.setLoaded("ogres.app.component.scene_objects.js");
import "./cljs-runtime/ogres.app.svg.js";
SHADOW_ENV.setLoaded("ogres.app.svg.js");
import "./cljs-runtime/module$node_modules$$rwh$react_keystrokes$dist$react_keystrokes_umd_cjs.js";
SHADOW_ENV.setLoaded("module$node_modules$$rwh$react_keystrokes$dist$react_keystrokes_umd_cjs.js");
import "./cljs-runtime/ogres.app.component.scene.js";
SHADOW_ENV.setLoaded("ogres.app.component.scene.js");
import "./cljs-runtime/ogres.app.component.scenes.js";
SHADOW_ENV.setLoaded("ogres.app.component.scenes.js");
import "./cljs-runtime/ogres.app.provider.shortcut.js";
SHADOW_ENV.setLoaded("ogres.app.provider.shortcut.js");
import "./cljs-runtime/ogres.app.component.toolbar.js";
SHADOW_ENV.setLoaded("ogres.app.component.toolbar.js");
import "./cljs-runtime/ogres.app.component.layout.js";
SHADOW_ENV.setLoaded("ogres.app.component.layout.js");
import "./cljs-runtime/ogres.app.dom.js";
SHADOW_ENV.setLoaded("ogres.app.dom.js");
import "./cljs-runtime/ogres.app.provider.cursor.js";
SHADOW_ENV.setLoaded("ogres.app.provider.cursor.js");
import "./cljs-runtime/ogres.app.provider.window.js";
SHADOW_ENV.setLoaded("ogres.app.provider.window.js");
import "./cljs-runtime/ogres.app.session.js";
SHADOW_ENV.setLoaded("ogres.app.session.js");
import "./cljs-runtime/ogres.app.core.js";
SHADOW_ENV.setLoaded("ogres.app.core.js");
import "./cljs-runtime/shadow.module.ogres.app.append.js";
SHADOW_ENV.setLoaded("shadow.module.ogres.app.append.js");


shadow.cljs.devtools.client.env.module_loaded("ogres.app");